### ISSUE TITLE
Empty DictField in ListField

### ISSUE THREAD

**Issue by ribx** [Scille/umongo#105]
When I give an empty dict ("{}") to a DictField inside a ListField, I get this error when trying to save the object:

> bson.errors.InvalidDocument: Cannot encode object: <marshmallow.missing>

A minimal example to reproduce:

```
... initialize db ...
from umongo import fields, Document
@instance.register
class ListTest(Document):
    dict = fields.ListField(fields.DictField())

new = ListTest(dict=[{}])
new.commit()
```

The problem is, that the _serialize_to_mongo of DictField replaces empty dicts with the missing object:

```
def _serialize_to_mongo(self, obj):
    if not obj:
        return missing
    return dict(obj)
```

See http://umongo.readthedocs.io/en/latest/_modules/umongo/fields.html#DictField

Why isn't it possible to save an empty Dict? Especially in a ListField there is a difference between having an empty dict and not having an object at all.

**Comment by lafrech** [comment]
I modified `_serialize_to_mongo` like this: 

```python
    def _serialize_to_mongo(self, obj):
        if obj is None:
            return missing
        return dict(obj)
```

It only breaks the test that checks precisely the behavior I'm changing: 

```
        # Empty dict is considered as missing field
        d2.set('dict', {})
>       assert d2.to_mongo() == {}
E       AssertionError: assert {'in_mongo_dict': {}} == {}
E         Left contains more items:
E         {'in_mongo_dict': {}}
E         Use -v to get the full diff
```

Serializing empty `dict` as `{}` rather than missing seems reasonable to me, not only in the "`dict` in the `list`" case.

@touilleMan, any opinion about this?

**Comment by touilleMan** [comment]
Seems pretty reasonable to me, @lafrech feel free to make this change into the master ;-)

**Comment by lafrech** [comment]
Should we do the same for `ListField`?

**Comment by touilleMan** [comment]
sure

**Comment by lafrech** [comment]
Hmmm, I looked into it and I'm in doubt.

umongo deserializes missing `dict`s as empty `dict`s. 

If the data is missing in the DB, when instantiating the object from DB, we get an empty `dict`. Let's say an empty `dict` should be serialized as `{}` rather than `missing`, then `to_mongo()` will spit a different content that was fetched from DB:

```python
        d3 = MyDataProxy()
        d3.from_mongo({})
        assert isinstance(d3.get('dict'), Dict)
>       assert d3.to_mongo() == {}
E       AssertionError: assert {'in_mongo_dict': {}} == {}
```

We didn't modify the object, but its DB representation is about to be modified. In fact, saving the object would not modify the data in DB because the field is not marked as modified and `commit` calls `to_mongo` with `update=True`. But this sounds inconsistent anyway.

```python
        assert d3.to_mongo() == {'in_mongo_dict': {}}
        assert d3.to_mongo(update=True) is None
```

`to_mongo(update=True)` returns `None` because the field was not marked as modified, but `to_mongo()` thinks differently.

I'm not sure how much of an issue that is.

Here's the change: https://github.com/Scille/umongo/compare/master...Nobatek:serialize_empty_dict.

**Comment by touilleMan** [comment]
I think we can solve this by modifying the `data_object.Dict` implementation to store a `missing_in_db` boolean:

```
class DictField(BaseField, ma_fields.Dict):

    def _serialize_to_mongo(self, obj):
        return missing if obj.missing_in_db and not obj else dict(obj)

    def _deserialize_from_mongo(self, value):
        return Dict(value)

...

class Dict(BaseDataObject, dict):

    __slots__ = ('_modified', 'missing_in_db')

    def __init__(self, *args, **kwargs):
        self._modified = False
        super().__init__(*args, **kwargs)
        self.missing_in_db = (len(args) == 1 and args[0] is missing)

    ...
```

**Comment by lafrech** [comment]
Not quite.

Consider the following case:

- The object is initialized with the attribute missing. The fields defaults to empty structure.
- Some data is added to the field. This is seamless due to the default above.
- The data is removed.

What should the state of the field be? Empty or missing? In fact, I don't know. With the fix above, it would be missing.

Note this applies to `List` as well.

I think the original sin comes from the default value. As long as we decide that default is an empty list, we lose the difference between missing list and empty list. I'd rather not implement the patch proposed in https://github.com/Scille/umongo/issues/105#issuecomment-297261688. IIUC, it just adds a broken layer on a broken logic.

If I'm not mistaken, the default value only serves the purpose of allowing a user to append seamlessly on a missing list. Maybe this use case is not that useful. I mean, if I instantiate an object with a missing list, I should not append.

```py
my_obj = MyObj()
assert my_obj.my_list == None
# Can't append, need to provide a list
my_obj.my_list = [12]
```

I didn't do extensive checks, but removing the `default`/`missing` values in `List`/`Dict` seems reasonable to me. This would be a breaking change. It could be done in the same major version as the `default`/`missing` rework (#107).

And we could also apply the patch in https://github.com/Scille/umongo/issues/105#issuecomment-297023891 to both `List` and `Dict`.

Feedback welcome.
