### ISSUE TITLE
how to do back-reference? 

### ISSUE THREAD

**Issue by mandarup** [Scille/umongo#141]
is there a way to add back referencing ? if not what is the umongo-way of doing this? any examples? 

e.g. I found this example for mongoengine : 

    replies = db.relationship(
        'Comment', backref=db.backref('parent', remote_side=[id]),
         lazy='dynamic')

**Comment by touilleMan** [comment]
Backreference is not something mongodb allows you to do.
This means this feature is provided by mongoengine itself and not the database which is really wrong because you don't have atomicity on this (so if something goes wrong you can end up with your db in an inconsistent state and be very puzzled how to understand&fix this given it all depend on implementation details inside mongoengine)

If you want to do back reference in mongo I suggest you implement it yourself, this way you can be aware of the possibilities and limitations of your solution and tune it for your usecase.
