### ISSUE TITLE
ValueError: microsecond must be in 0..999999

### ISSUE THREAD

**Issue by enugentdt** [Scille/umongo#189]
Hello, all

I've got a new error after the v2.0.0 milestone, likely relating to #172. Here's the error text:

```python
  File "/Users/space/Documents/Programming/dt-blog-platform/api-server/db/objs.py", line 268, in commit
    self.updatedon = datetime.datetime.utcnow()
  File "/var/root/.local/share/virtualenvs/api-server-DI-zCP9m/lib/python3.6/site-packages/umongo/document.py", line 295, in __setattr__
    self._data.set(name, value, to_raise=AttributeError)
  File "/var/root/.local/share/virtualenvs/api-server-DI-zCP9m/lib/python3.6/site-packages/umongo/data_proxy.py", line 152, in set
    value = field._deserialize(value, name, None)
  File "/var/root/.local/share/virtualenvs/api-server-DI-zCP9m/lib/python3.6/site-packages/umongo/fields.py", line 245, in _deserialize
    return ret.replace(microsecond=round(ret.microsecond, -3))
ValueError: microsecond must be in 0..999999
```

My guess is something funky is going on either with my system, or maybe the round isn't working properly? Not too sure, but this should be a simple one.

The way I did this is set a `StrictDateTimeField` equal to `datetime.datetime.utcnow()` in an overriden `commit` method. Ex:

```python
@instance.register
class Foo(Document):
    name = fields.StringField()
    updatedon = fields.StrictDateTimeField()

    def commit(self, *args, **kwargs):
        self.updatedon = datetime.datetime.utcnow()
        return super(Foo, self).commit(*args, **kwargs)
```

This error happens when calling the commit method on the object.

Thanks in advance!

**Comment by lafrech** [comment]
Thanks for reporting.

This is due to millisecond being rounded to `1000000`. In this case, second should be incremented and millisecond set to `0`.

This is my mistake. It already happened to me in another context and I forget about it when submitting #172. Sorry about that.

I submitted #190 to fix this. @enugentdt, do you think you could check if it solves your problem?

**Comment by enugentdt** [comment]
Can do. I’ll have a report for you tomorrow morning EDT

Thanks,
Eamonn

**Comment by enugentdt** [comment]
Looks like the pull fixed the issue. I wasn't able to repro it (though it is a bit of a "special" issue, so it's possible I just never had the right conditions.)

Seems good, @lafrech!

Thanks

**Comment by lafrech** [comment]
Yeah, I was wondering how you would reproduce that. It's a 1/2000 likelihood as it only happens if the milliseconds round to 1000.

Waiting on @touilleMan's thoughts on the PR. If he doesn't have the time to look at it, I'll merge it myself as a bugfix soon. The fix it the correct one. The two implementations are functionally identical, it's mostly a matter of preference and it can always be reworked afterwards.

**Comment by enugentdt** [comment]
Heh, I said I'd try it out and had the same thought. Your test case should be more than enough.

My current "best guess" on how to test it is literally to merge it, have it in a new pip release, and use it in prod for a while. If my cron tasks start to fail, well, I think we know where the culprit is.

**Comment by lafrech** [comment]
I prefer to rely on comprehensive testing rather than release into the wild until someone complains about a broken app. But frankly, I'm confident about the patch.

**Comment by vbukhonov** [comment]
Still an issue
