### ISSUE TITLE
3.0.0b12 possible regression with lazy loaders

### ISSUE THREAD

**Issue by voglster** [Scille/umongo#316]
Maybe I am doing this wrong,

```
from pymongo import MongoClient
from umongo import Instance

db = MongoClient("mongodb+srv://USER:PW@SOMETHING_MONGO.mongodb.net/")["insert_cool_db_name"]

instance = Instance(db)
```
Results in a:

TypeError: Can't instantiate abstract class Instance with abstract methods is_compatible_with

This does not happen in 3.0.0b11, is there a new way to instantiate a lazy load?

**Comment by voglster** [comment]
Reading the latest few commits it looks like instance was updated a bit to handle is_compatible_with

I'm going to hazard a guess that we can follow the example in conftest.py line 11

```
instance = Instance(db)
```

becomes

```
instance = Instance.from_db(db)
```

the quick example on the main github page does this and will probably trip up any new users

```
db = MongoClient().test
instance = Instance(db)
```

**Comment by lafrech** [comment]
Hi.

In my rush to publish 3.0.0b12, I omitted to update the docs. Sorry about that. I just pushed a commit with a doc update.

I kept ``from_db`` constructor but I don't advocate for its usage in the docs. Since the driver kind (pymongo vs. motor,...) is known, it is more explicit to import the specific instance class.

I tried to explain the change in #313
