### ISSUE TITLE
DateTime and timezone awareness

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#44]
I'm pulling my hair with datetime TZ awareness issues.

I initiate the connection to MongoDB with `tz_aware = False`. I'm no expert about this, and I had never thought much about it before now, but from what I gathered, it seems like a reasonable choice to make. Besides, it's `pymongo`'s default (but flask-PyMongo's hardcodes `tz_aware` to `True`).

When a document is pulled from the DB, its `DateTimeField` attribute's TZ awareness depends only on `MongoClient`'s `tz_aware` parameter (no Marshmallow schema involved):

`tz_aware=True` -> pymongo provides an aware datetime -> umongo returns an aware datetime
`tz_aware=False` -> pymongo provides a naive datetime -> umongo returns a naive datetime

This is one more reason to set `tz_aware = False`, because I'm passing a document/object to a lib that expects a naive timezone. (OAuth2 lib expects `expires` timestamp to be naive and compares it to `datetime.utcnow()` ([see code](https://github.com/lepture/flask-oauthlib/blob/e1bb478b2015239dd12f1d3ee13fb2627a5a3407/flask_oauthlib/provider/oauth2.py#L789)).) I suppose I could alternatively modify my getters to make all `datetime`s naive before returning tokens/grants, but on some use cases, it could get cumbersome.

Marshmallow, however, returns every `datetime` as TZ aware ([doc](http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.fields.DateTime)). For this reason, umongo's `DateTimeField`'s `_deserialize` method returns a TZ aware `datetime`. Since I'm using it (via webargs) to parse the inputs to my API, I'm getting TZ aware `datetime`s. Likewise, calling `load()` on a document will use `_deserialize` and result in a TZ aware `datetime`.

So if I load a date, it becomes TZ aware. Therefore, to compare it to a date from the database, this one needs to be aware as well.

Should I understand that umongo is meant to be used with `tz_aware=True`, so that dates fetched from the database can be compared to dates loaded thought Marshmallow schemas?

Could there be a flag/meta allowing to specify if a `DateTimeField` should return a naive `datetime`?

I made a quick and dirty patch to `DateTime`'s `_deserialize` to remove the TZ from the returned output.

```py
    dt = super()._deserialize(value, attr, data)
    return dt.replace(tzinfo=None)
```

This seems to work on my use case. However, the day we complete pure Marshmallow schema export, the exported schema I pass to webargs for API input parsing won't have that feature. Unless this is added to Marshmallow as well. (I asked there about it there: https://github.com/marshmallow-code/marshmallow/issues/520.)

Feedback welcome. Those TZ issues are new to me, so I may be totally misguided.

**Comment by touilleMan** [comment]
First I advice you not to use flask-pymongo, specifically because it hardcodes configuration behind your back.

Second advice is to always work with UTC. This way a TZ naive datetime is just an implicit UTC datetime, so you can use TZ naive everywhere and forget about this once and for all ;-)

Consider it's your frontend's job to display date in the user's timezone.

You can compare this method as the Python3 unicode-everywhere policy: you deal with encoding and conversion only when talking to the outside world.

Now for the umongo part...

It seems marshmallow allow to deserialize both timezone aware and naive dates (see https://github.com/Scille/umongo/blob/master/tests/test_fields.py#L90)

What I agree though is deserializing a TZ aware date into umongo should end up with a TZ naive datetime in order not to mix TZ aware and TZ naive (typically for fields comparisons).
So I think we could add a `tz_aware` attribute to the `DateTimeField` and `LocalDateTimeField`. If `True` all deserialized date would be with a timezone (which would be utc if the date was initially tz naive). The default would be `False` and so would display all dates as tz naive.

The pymongo's `tz_aware` would not be taken into account given it's just a way to return tz aware datetime by providing a zero-offset timezone.


```python
    dt = super()._deserialize(value, attr, data)
    return dt.replace(tzinfo=None)
```
I don't think this would work: you remove the timezone, so if the date is `2014-08-08T12:00:00+02:00` you end up with `2014-08-08T12:00:00` where the UTC version would be `2014-08-08T10:00:00` !

**Comment by lafrech** [comment]
> First I advice you not to use flask-pymongo, specifically because it hardcodes configuration behind your back.

I don't, but I peeked into it to get inspiration for the configuration parsing and I noticed `tz_aware` was forced to True. I figured they might have a reason.

> Second advice is to always work with UTC. This way a TZ naive datetime is just an implicit UTC datetime, so you can use TZ naive everywhere and forget about this once and for all ;-)

Yes, I totally agree. I like the UTC everywhere policy. But all UTC does not mean all naive and you can still encounter naive (considered UTC) and aware (explicitly UTC) datetimes.

Are you suggesting I should always work with naive datetimes in my business code (and therefore keep default `False` value for `tz_aware`)?

It seems to be good practice, however, to specify UTC explicitly in the API outputs, so the datetime has to become UTC aware when reaching the outside world. (Using Marshmallow to marshall the date in the json response makes it TZ aware, so this is covered already.)

A little background info for myself or anyone passing by (you know that, already): 

pymongo's documention about [Datetimes and Timezones](https://api.mongodb.com/python/current/examples/datetimes.html) helped me understand the concepts and the behavior in MongoDB and PyMongo.

Mongo always stores dates with no timezone information (assuming UTC, but I suppose you could use your own convention). PyMongo always stores UTC `datetime`s.

- If given a naive `datetime`, it assumes UTC and stores it as is
- If given an aware `datetime`, it converts it to UTC before storing

When retrieving a date, depending on the `tz_aware` flag, it will return a naive or an aware `datetime`.

> It seems marshmallow allow to deserialize both timezone aware and naive dates (see https://github.com/Scille/umongo/blob/master/tests/test_fields.py#L90)

You're right. The doc is ambiguous about this and I understood otherwise (see https://github.com/marshmallow-code/marshmallow/issues/309#issuecomment-244076069).

> What I agree though is deserializing a TZ aware date into umongo should end up with a TZ naive datetime in order not to mix TZ aware and TZ naive (typically for fields comparisons).
So I think we could add a tz_aware attribute to the DateTimeField and LocalDateTimeField. If True all deserialized date would be with a timezone (which would be utc if the date was initially tz naive). The default would be False and so would display all dates as tz naive.

First draft here: https://github.com/Scille/umongo/pull/46.

> The pymongo's `tz_aware` would not be taken into account given it's just a way to return tz aware datetime by providing a zero-offset timezone.

I don't understand this part. This parameter still affects `datetime`s read from DB. I only modified `_deserialize` in `DateTimeField`.

We may also override `_deserialize_from_mongo` but why not rely on pymongo's `tz_aware`? That's what it is here for.

> I don't think this would work: you remove the timezone, so if the date is `2014-08-08T12:00:00+02:00` you end up with `2014-08-08T12:00:00` where the UTC version would be `2014-08-08T10:00:00` !

I didn't think of this case, because I'm PyMongo focused. PyMongo only stores UTC dates with no offset. That is, it converts them into UTC before storing them in DB.

```py
tz = pytz.timezone('Europe/Paris')

db.tzdemo.insert_one({
    "test UTC": datetime.datetime.utcnow(),
    "test local": tz.localize(datetime.datetime.utcnow()),
})
```

This is what is written in DB:

```
    { "_id" : ObjectId("57c7f7c427b61331070ef17e"),
      "test UTC" : ISODate("2016-09-01T09:41:24.789Z"),
      "test local" : ISODate("2016-09-01T07:41:24.789Z")
    }
```

I don't think you can store `2014-08-08T12:00:00+02:00` with PyMongo. But maybe this is possible with other drivers (python or even other language?). I've taken this into account in the draft I proposed. The date is converted to UTC before the TZ info is removed.

Thank you very much for your feedback. It is much clearer now.

**Comment by touilleMan** [comment]
> Are you suggesting I should always work with naive datetimes in my business code (and therefore keep default False value for tz_aware)?

Yep ! That's my way of doing it ^^
Other way would be to keep everything with UTC timezone (I agree this is a cleaner approach, however given `datetime.utcnow()` provides timezone-naive, I started going full timezone-naive instead of using `datetime.datetime.now(datetime.timezone.utc)`)

I don't see any practical reason to work with something other than UTC in an application (client need timezone given people _are_ in timezones, but server doesn't care about this), so in a full utc world, timezone-naive or utc-timezone (using pymongo's `tz_aware`) is the same. Choose one and stick to hit :+1: 

> The pymongo's tz_aware would not be taken into account given it's just a way to return tz aware datetime by providing a zero-offset timezone.

MongoDB doesn't change it way to store data when selecting pymongo's `tz_aware` (not the umongo's one we are talking about implementing). So pymongo's `tz_aware` is just a convenient way to get datetime with timezone (but a fixed utc timezone, no matter what timezone you send to the database in the first place)

> First draft here: #46.

Niiiiiice ;-)

> We may also override _deserialize_from_mongo but why not rely on pymongo's tz_aware? That's what it is here for.

Pymongo too low level for this task: it only help you with the _mongo world_, data coming from _user world_ are to be deserialized by marshmallow which actually returns timezone aware or naive *depending of the input !!!*
This is indeed really bad given you can make the application crash by a comparison between aware and naive dates...
So the idea is to move this logic into the core of umongo (and provide a custom `StrictDatetime` field for marshmallow when exporting the field). This way no matter the user entry, the deserialized output would always be 1) timezone aware/naive datetime depending of the field configuration 2) error due to bad input ;-)

Beside a user may want one field timezone naive and another timezone aware, so we need this configuration on a per field configuration option.

> I've taken this into account in the draft I proposed. The date is converted to UTC before the TZ info is removed.

Just FYI, I've already implemented in a project a marshmallow field always returning timezone naive in UTC base:

```python
class UTCTZnaiveDateTime(DateTime):

    """
    DateTime object in UTC with no tzinfo
    """

    def _deserialize(self, value, attr, data):
        value = super()._deserialize(value, attr, data)
        if value and value.tzinfo:
            value = (value - value.utcoffset()).replace(tzinfo=None)
        return value
```

**Comment by lafrech** [comment]
> Pymongo too low level for this task: it only helps you with the mongo world, data coming from user world are to be deserialized by marshmallow which actually returns timezone aware or naive depending of the input !!!

Yes, I understand this.

We need to overload `_deserialize` to enforce naiveness on data from the outside world. I was wondering about the data from the DB. Leaving `tz_aware` `False` in the connection is enough to ensure the dates from the DB are naive, but on second thought, we should probably also ensure this in `_deserialize_from_mongo` to make sure all dates in the OO world are naive (or aware, depending on the use choice) whatever is set in the connection client. Besides, this would work for any driver.

While we're at it, we may also add a parameter to allow the user to choose the format to serialize to the outside world (currently aware by default, due to Marshmallow).

To summarize, we could have

- `load_as_tz_aware` or `deserialize_as_tz_aware`: whether dates should be aware or naive when loaded from Mongo or from outside world. Affects both `_deserialize` and `_deserialize_from_mongo`. There is no need to have two different parameters here, as it wouldn't make sense to make a different choice for them.

- `dump_as_tz_aware` or `serialize_as_tz_aware`: whether dates should be aware or naive when leaving to the outside world. Affects `_serialize`.

In this model, `tz_aware` in MongoClient has no effect, except on data from the aggregation framework (we might want to warn the user about that corner case).

> Beside a user may want one field timezone naive and another timezone aware, so we need this configuration on a per field configuration option.

Absolutely. Those parameters are field parameters.

> ```py
>        if value and value.tzinfo:
>            value = (value - value.utcoffset()).replace(tzinfo=None)
> ```

Thanks for the example.

The test I made to check awareness is a bit more complex. I got it from [this SO post](http://stackoverflow.com/a/27596917/4653485). The difference would be for dates with `tzinfo != None` but `tzinfo.utcoffset()` == None.

```py
if date.tzinfo is not None and date.tzinfo.utcoffset(date) is not None
```
I'll try to rework my draft.

**Comment by lafrech** [comment]
I rebased and updated my draft to introduce `StrictDateTimeField`.

I only implemented `load_as_tz_aware`. `dump_as_tz_aware` is more complex as it needs to modify serialized data from Marshmallow or hack into Marshmallow datetime management.

I didn't do `StrictLocalDateTimeField` either for now.

**Comment by lafrech** [comment]
Closing this as StrictDateTimeField has been merged (https://github.com/Scille/umongo/pull/46).

It can be reopened the day someone needs `dump_as_tz_aware`.

**Comment by nedwill** [comment]
Hey, I know this is closed but I came across this issue, and noticed that in [the merged fix](https://github.com/Nobatek/umongo/blob/14ec7e40ca517071d9374af39f8409223e097253/umongo/marshmallow_bonus.py#L111), you're calling `date.astimezone(tzutc())` as if it has side effects, but it does not [according to the Python docs](https://docs.python.org/2/library/datetime.html#datetime.datetime.astimezone).

**Comment by lafrech** [comment]
@nedwill, I don't fully understand your comment, but while investigating this I found an issue and sent a PR: https://github.com/Scille/umongo/pull/75. Was that your point or is there anything else?

**Comment by nedwill** [comment]
Yeah, that's what I meant - `date.astimezone` returns a new date, it doesn't have side effects/mutate the date.

**Comment by lafrech** [comment]
Thanks @nedwill for pointing this.

BTW, I just found out a surprising behaviour of `DateTime` field in Marshmallow that also affects `StrictDateTimeField`. See https://github.com/marshmallow-code/marshmallow/issues/556

```py
f = fields.DateTime()
f.deserialize('1916')
# datetime.datetime(1916, 11, 30, 0, 0)
f.deserialize('1916-2')
# datetime.datetime(1916, 2, 29, 0, 0)
f.deserialize('1916-3')
# datetime.datetime(1916, 3, 30, 0, 0)
```

Those inputs should be rejected or default to something more predictable.

It is not _that_ bad. It won't break the application. But until it's fixed upstream, it's good to know.

**Comment by touilleMan** [comment]
#75 is merged, @nedwill thanks for pointing this 👍
