### ISSUE TITLE
Auto-indexes in Instance?

### ISSUE THREAD

**Issue by lafrech** [Scille/umongo#81]
What would you think about a kind of semi-automatic opt-in indexes generation like this?

```py
# Mark Document for indexing
@instance.register(auto_index=True)
class MyDocument(Document):
...
```
In Instance:

```py
    def register(self, template, as_attribute=True, auto_index=False):
        # Retrieve the template if another implementation has been provided instead
        template = get_template(template)
        if issubclass(template, DocumentTemplate):
            implementation = self._register_doc(template)
+           if auto_index:
+               self._auto_indexes.append(implementation)
        else:  # EmbeddedDocumentTemplate
+           if auto_index:
+               raise SomeException
            implementation = self._register_embedded_doc(template)
        if as_attribute:
            setattr(self, implementation.__name__, implementation)
        return implementation

+   def ensure_indexes(self):
+       for doc in self._auto_indexes:
+           doc.ensure_indexes()
```

**Comment by lafrech** [comment]
I'm working on a better approach

- using `Meta` in `Document` to specify `auto_indexes`
- using an `auto_indexes` attribute in `LazyInstance` to force `auto_indexes` on all `Document`s at `init`

**Comment by touilleMan** [comment]
`ensure_indexes` has been dropped by pymongo due to potential concurrency issues when dropping & recreating rapidly the database. This leave us only with `create_indexes` which doesn't internally hold a timer, meaning each request should send a `create_indexes` first before actually send the request.

This is currently what happens with [mongoengine + pymongo>=3](https://github.com/MongoEngine/mongoengine/issues/1446), so I think requiring user to explicitly create the indexes makes him to to integrated it into workflow instead of relying on half broken magic.
